spring:
  application:
    name: library
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/tasktales
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
